#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative 'rain_risk'
require 'curses'

Curses.init_screen
Curses.curs_set(0)
begin
  ship = ::RainRisk::Ship.new
  ship.waypoint = ::RainRisk::Waypoint.new(1, 10)
  ship.extend(::RainRisk::NavigationWithWaypoint)

  start_north = 20_000
  start_east  = 60_000
  scale       = 1000

  Curses.setpos((start_north / scale).to_i, (start_east / scale).to_i)

  ship.navigate(File.readlines(ARGV[0])) do
    Curses.clear
    Curses.setpos((start_north + ship.north / scale).to_i,
                  (start_east + ship.east / scale).to_i)
    # Curses.addstr(ship.to_s)

    Curses.setpos(((start_north + ship.north + ship.waypoint.north) / scale).to_i,
                  ((start_east + ship.east + ship.waypoint.east) / scale).to_i)
    Curses.addstr(ship.to_s)
    Curses.refresh
    sleep 0.05
  end

  Curses.getch  # Waiting for a pressed key to exit
ensure
  Curses.close_screen
end
